Fix types conflicts caused by types installed transiently
All @types packages are included by default when compiling:

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

Unfortunately some types installed transiently are conflicting with @types/node and
causing builds to fail with the following error/s:

```
node_modules/@types/webpack-env/index.d.ts(282,13): error TS2403:
Subsequent variable declarations must have the same type.
Variable 'require' must be of type 'Require', but here has type 'NodeRequire'.
```

This change ensures only the types packages we want to load are loaded. This does not
affect how types are loaded when importing a package.

cc https://github.com/microsoft/TypeScript/issues/18588